import { useState } from 'react'
import type { AnswerFeedback, InterviewQuestion, InterviewTurn, Job, Profile, Settings } from '../types'
import { generateJson } from '../lib/llm'
import { INTERVIEW_FEEDBACK_SYSTEM, INTERVIEW_QUESTIONS_SYSTEM } from '../lib/prompts'
import { Badge, Button, Card, ErrorNote, Field, SectionTitle, Spinner, inputCls, textareaCls } from '../components/ui'

const KIND_TONE = { behavioral: 'blue', technical: 'amber', role: 'green' } as const

export default function InterviewScreen({
  settings,
  profile,
  jobs,
  initialJobId = '',
}: {
  settings: Settings
  profile: Profile
  jobs: Job[]
  initialJobId?: string
}) {
  const [jobId, setJobId] = useState(initialJobId)
  const [role, setRole] = useState('')
  const [turns, setTurns] = useState<InterviewTurn[]>([])
  const [current, setCurrent] = useState(0)
  const [answer, setAnswer] = useState('')
  const [busy, setBusy] = useState<'questions' | 'feedback' | null>(null)
  const [error, setError] = useState('')

  const job = jobs.find((j) => j.id === jobId)
  const roleLabel = job ? `${job.title} at ${job.company}` : role

  const context = () =>
    `ROLE: ${roleLabel}\n${job?.description ? `JOB DESCRIPTION:\n${job.description.slice(0, 4000)}\n` : ''}${
      profile.resumeText ? `CANDIDATE RESUME:\n${profile.resumeText.slice(0, 4000)}` : ''
    }`

  const start = async () => {
    setError('')
    if (!roleLabel.trim()) {
      setError('Pick a saved job or type a role to practice for.')
      return
    }
    // Questions already generated by the One-Tap pipeline — reuse instead of re-billing the user's key.
    if (turns.length === 0 && job?.interviewPrep?.length) {
      setTurns(job.interviewPrep.map((q) => ({ question: q, answer: '' })))
      setCurrent(0)
      setAnswer('')
      return
    }
    setBusy('questions')
    try {
      const data = await generateJson<{ questions: InterviewQuestion[] }>(
        settings,
        INTERVIEW_QUESTIONS_SYSTEM,
        context(),
      )
      setTurns(data.questions.map((q) => ({ question: q, answer: '' })))
      setCurrent(0)
      setAnswer('')
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Could not generate questions.')
    } finally {
      setBusy(null)
    }
  }

  const submitAnswer = async () => {
    if (!answer.trim()) return
    setError('')
    setBusy('feedback')
    try {
      const turn = turns[current]
      const feedback = await generateJson<AnswerFeedback>(
        settings,
        INTERVIEW_FEEDBACK_SYSTEM,
        `${context()}\n\nQUESTION: ${turn.question.question}\n\nCANDIDATE'S ANSWER:\n${answer}`,
      )
      setTurns(turns.map((t, i) => (i === current ? { ...t, answer, feedback } : t)))
      setAnswer('')
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Could not score the answer.')
    } finally {
      setBusy(null)
    }
  }

  const answered = turns.filter((t) => t.feedback)
  const avg = answered.length
    ? Math.round((answered.reduce((s, t) => s + (t.feedback?.score ?? 0), 0) / answered.length) * 10) / 10
    : null
  const turn = turns[current]

  return (
    <div className="mx-auto max-w-3xl space-y-6">
      <SectionTitle sub="Real practice with honest feedback — before the interview, not whispered answers during it. Questions adapt to the role and your actual resume.">
        Mock interview
      </SectionTitle>

      <Card className="space-y-4">
        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
          <Field label="Practice for a saved job">
            <select className={inputCls} value={jobId} onChange={(e) => { setJobId(e.target.value); setRole('') }}>
              <option value="">— or type a role instead —</option>
              {jobs.map((j) => (
                <option key={j.id} value={j.id}>{j.title || 'Untitled'} @ {j.company || '?'}</option>
              ))}
            </select>
          </Field>
          <Field label="Or any role">
            <input
              className={inputCls}
              placeholder="e.g. ICU Nurse, High School Teacher, Backend Engineer"
              value={role}
              onChange={(e) => { setRole(e.target.value); setJobId('') }}
            />
          </Field>
        </div>
        <div className="flex items-center gap-3">
          <Button onClick={start} disabled={busy !== null}>
            {turns.length ? 'New session' : 'Start practice'}
          </Button>
          {busy === 'questions' && <Spinner label="Writing questions…" />}
          {avg !== null && <Badge tone="blue">Session average: {avg}/10 over {answered.length} answers</Badge>}
        </div>
        {error && <ErrorNote message={error} />}
      </Card>

      {turns.length > 0 && (
        <>
          <div className="flex flex-wrap gap-1.5">
            {turns.map((t, i) => (
              <button
                key={i}
                onClick={() => { setCurrent(i); setAnswer('') }}
                className={`h-8 w-8 rounded-lg text-xs font-semibold transition-colors ${
                  i === current
                    ? 'bg-slate-900 text-white'
                    : t.feedback
                      ? t.feedback.score >= 7
                        ? 'bg-emerald-100 text-emerald-800'
                        : 'bg-amber-100 text-amber-800'
                      : 'bg-slate-100 text-slate-500 hover:bg-slate-200'
                }`}
              >
                {t.feedback ? t.feedback.score : i + 1}
              </button>
            ))}
          </div>

          {turn && (
            <Card className="space-y-4">
              <div className="flex items-start justify-between gap-3">
                <p className="text-base font-medium text-slate-900">{turn.question.question}</p>
                <Badge tone={KIND_TONE[turn.question.kind] ?? 'slate'}>{turn.question.kind}</Badge>
              </div>

              {!turn.feedback ? (
                <>
                  <textarea
                    className={textareaCls}
                    rows={6}
                    placeholder="Answer out loud first if you can, then type what you said…"
                    value={answer}
                    onChange={(e) => setAnswer(e.target.value)}
                  />
                  <div className="flex items-center gap-3">
                    <Button onClick={submitAnswer} disabled={busy !== null || !answer.trim()}>
                      Get feedback
                    </Button>
                    {busy === 'feedback' && <Spinner label="Scoring…" />}
                  </div>
                </>
              ) : (
                <div className="space-y-4">
                  <div className="rounded-lg bg-slate-50 p-3 text-sm text-slate-600">
                    <span className="font-medium text-slate-800">Your answer: </span>
                    {turn.answer}
                  </div>
                  <div className="flex items-center gap-2">
                    <span className={`text-2xl font-bold ${turn.feedback.score >= 7 ? 'text-emerald-600' : turn.feedback.score >= 5 ? 'text-amber-600' : 'text-red-600'}`}>
                      {turn.feedback.score}/10
                    </span>
                  </div>
                  <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                    <div>
                      <h4 className="mb-1 text-sm font-semibold text-emerald-700">What worked</h4>
                      <ul className="list-disc space-y-1 pl-5 text-sm text-slate-600">
                        {turn.feedback.strengths.map((s, i) => <li key={i}>{s}</li>)}
                      </ul>
                    </div>
                    <div>
                      <h4 className="mb-1 text-sm font-semibold text-amber-700">To improve</h4>
                      <ul className="list-disc space-y-1 pl-5 text-sm text-slate-600">
                        {turn.feedback.improvements.map((s, i) => <li key={i}>{s}</li>)}
                      </ul>
                    </div>
                  </div>
                  <div>
                    <h4 className="mb-1 text-sm font-semibold text-slate-900">A stronger version of your answer</h4>
                    <p className="rounded-lg bg-emerald-50 p-3 text-sm leading-relaxed text-slate-700">
                      {turn.feedback.better_answer}
                    </p>
                  </div>
                  {current < turns.length - 1 && (
                    <Button onClick={() => { setCurrent(current + 1); setAnswer('') }}>Next question →</Button>
                  )}
                </div>
              )}
            </Card>
          )}
        </>
      )}
    </div>
  )
}
